### PR TITLE
Clean up deployment, and match it to README process.

### PR DESCRIPTION
**Pull request by gfr10598**
Travis is currently somewhat broken, so I can't debug a failure late in the travis build process, but I think this is in reasonably good shape to review.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/npad-support/27)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[.travis.yml, line 6 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBAjvK1lKhnGoH6l81:-KeBAjvK1lKhnGoH6l82:b-b2r1qi) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L6)):*
> ```YAML
> #   Handles gcloud credentials.
> #   On successful build (on pushes only) deploys rpm to
> #   legacy-rpms-mlab-xxx.
> ```

Maybe just "deploys rpm to a GCS bucket". The specific bucket is named below.

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBPLV7s_PJclsyiHF3:-KeBPLV8Pv0xIshruEir:b-hfzzzw) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L12)):*
> ```YAML
> #       legacy-rpms-mlab-staging, to testing folder.
> #     * On tagged builds from m-lab repo, pushes rpm to
> #       legacy-rpms-mlab-staging, to canary folder.
> ```

See comment below about calling this folder "staging" instead.

---

*[.travis.yml, line 38 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBLoDpGDKJWEam3CLi:-KeBLoDqdVY0HjUvppOK:bnub2bj) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L38)):*
> ```YAML
>    on:
>      all_branches: true
>      condition: $TRAVIS_REPO_SLUG != m-lab/npad-support
> ```

Without the individual account key, is this condition still possible? If individual account keys are bundled in the `.tar`, what are the steps for a new person adding their own key? Is this a configuration we wish to support? What if the condition matched `sandbox-*` branches?

---

*[.travis.yml, line 51 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBN3antrm6Fobur-vq:-KeBN3antrm6Fobur-vr:be9zwsx) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L51)):*
> ```YAML
>    skip_cleanup: true
> 
> # STAGING: Main repo, with tag --> deploy to staging/canary
> ```

Suggest phrasing as "deploy to staging for canary."

---

*[.travis.yml, line 53 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBNC52BVCDQkJIh6Vl:-KeBNC52BVCDQkJIh6Vm:b-2xl0nf) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L53)):*
> ```YAML
> # STAGING: Main repo, with tag --> deploy to staging/canary
> # These will later be promoted through a separate process from staging
> # to legacy-rpms-mlab-oti (or maybe legacy-rpms-mlab-prod ???
> ```

"mlab-oti" is an unfortunate barnacle. For consistency with the `<prefix>-<project>` convention, I'd like to advocate for "legacy-rpms-mlab-oti".

---

*[.travis.yml, line 59 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBP3SC_2SLKB0HrY4h:-KeBP3SC_2SLKB0HrY4i:btbpyyx) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L59)):*
> ```YAML
>      tags: true
>      condition: $TRAVIS_EVENT_TYPE = push
>    script: $TRAVIS_BUILD_DIR/travis/deploy.sh /tmp/legacy-rpm-writer.mlab-staging.json legacy-rpms-mlab-staging/canary
> ```

Maybe to match the current yum repo conventions, calling this location "staging" will be clearer. "Canary" is a state that's reached after passing through the "staging" repo today.

---

*[travis/decrypt.sh, line 9 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBPQudsKa7KXywYvj5:-KeBPQudsKa7KXywYvj6:bj60tql) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/travis/decrypt.sh#L9)):*
> ```Shell
> # from the same directory that the existing keys were generated from.
> #
> # In the event that the encryption keys are lost, there are a few
> ```

Thank you for these detailed notes.

---

*[travis/decrypt.sh, line 12 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBNlPlfDNtLOYbm-7c:-KeBNlPlfDNtLOYbm-7d:bozowre) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/travis/decrypt.sh#L12)):*
> ```Shell
> # steps that have to be taken to restore functionality.
> #  1. If the SA keys are available, skip to step 4.
> #  2. Create new service accounts for mlab-sandbox and mlab-staging,
> ```

I'm pretty sure it's possible to generate new keys for an existing service account (and probably invalidate the old keys).

---

*[travis/deploy.sh, line 18 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBOJDxkfXaBWyNxKff:-KeBOJDxkfXaBWyNxKfg:bpleoc2) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/travis/deploy.sh#L18)):*
> ```Shell
> gcloud auth activate-service-account --key-file "${KEYFILE}"
> 
> # For this to succeed, the provided keyfile must provide W access to the
> ```

I must have missed this originally. Technicality nit: my understanding of the SA mechanism and the bucket ACL is that the key is proof of identity. And, the bucket ACL provides W access to the service account.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/27)*

**Comment by gfr10598** [comment]
Review status: 2 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[.travis.yml, line 38 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBLoDpGDKJWEam3CLi:-KeEU4w_jrDB-2kkWZya:b-e0n6s3) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L38)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Without the individual account key, is this condition still possible? If individual account keys are bundled in the `.tar`, what are the steps for a new person adding their own key? Is this a configuration we wish to support? What if the condition matched `sandbox-*` branches?
</blockquote></details>

Yes, but not sure how much we want to support it.  It basically only works for someone who has the encryption keys.  I have the keys, and can push them to anyone else who would like to have them (at least for a limited time).  Added sandbox-*

---

*[.travis.yml, line 51 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBN3antrm6Fobur-vq:-KeEUedujnkO8dR_cK8n:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L51)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Suggest phrasing as "deploy to staging for canary."
</blockquote></details>

Done.

---

*[.travis.yml, line 53 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBNC52BVCDQkJIh6Vl:-KeEUfjK9Jj65KiNz2dI:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L53)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"mlab-oti" is an unfortunate barnacle. For consistency with the `<prefix>-<project>` convention, I'd like to advocate for "legacy-rpms-mlab-oti".
</blockquote></details>

Done.

---

*[.travis.yml, line 59 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBP3SC_2SLKB0HrY4h:-KeEUhcKQYociUB3ilrY:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L59)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Maybe to match the current yum repo conventions, calling this location "staging" will be clearer. "Canary" is a state that's reached after passing through the "staging" repo today.
</blockquote></details>

Done.

---

*[travis/decrypt.sh, line 12 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBNlPlfDNtLOYbm-7c:-KeEV6hI7NtByPaTvSXj:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/travis/decrypt.sh#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I'm pretty sure it's possible to generate new keys for an existing service account (and probably invalidate the old keys).
</blockquote></details>

Done.

---

*[travis/deploy.sh, line 18 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBOJDxkfXaBWyNxKff:-KeEVat4_2yUQY_SJQV8:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/travis/deploy.sh#L18)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I must have missed this originally. Technicality nit: my understanding of the SA mechanism and the bucket ACL is that the key is proof of identity. And, the bucket ACL provides W access to the service account.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/27)*

**Comment by stephen-soltesz** [comment]
Reviewed 1 of 3 files at r2, 2 of 3 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[.travis.yml, line 37 at r2](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeEoyqG0vtAfUWk-4UR:-KeEoyqG0vtAfUWk-4US:b256k5j) ([raw file](https://github.com/m-lab/npad-support/blob/1b4af85c6732f9d8782799a6963f4d2107baf615/.travis.yml#L37)):*
> ```YAML
>    on:
>      all_branches: true
>      condition: $TRAVIS_REPO_SLUG != m-lab/npad-support && $TRAVIS_BRANCH =~ sandbox-*
> ```

I imagined this would be `||` rather than `&&`. The thought being either we use the personal encryption key from forked repos, or we use the `m-lab/npad-support` key from `sandbox-*` branches in the npad-support repo.

---

*[README.md, line 22 at r3](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeEr9VoApfRwhQpUTT3:-KeEr9VoApfRwhQpUTT4:b-xdsnae) ([raw file](https://github.com/m-lab/npad-support/blob/efb0795dc80aefa8b3f2b840b3cf52b46be04f0d/README.md#L22)):*
> ```Markdown
> verification steps.  With the slightly modified travis deployment rules,
> we could, for example:
> * Developer uses a sandbox-* branch, so rpm is pushed to 'private'
> ```

s/private/testing/ ?

Does this section need any other updates yet?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/27)*

**Comment by gfr10598** [comment]
Review status: 4 of 6 files reviewed at latest revision, 11 unresolved discussions.

---

*[.travis.yml, line 6 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBAjvK1lKhnGoH6l81:-KeEsYV9-X5UzubvCsAo:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L6)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Maybe just "deploys rpm to a GCS bucket". The specific bucket is named below.
</blockquote></details>

Done.

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBPLV7s_PJclsyiHF3:-KeEsYqLzMDo31yLiVQk:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/.travis.yml#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

See comment below about calling this folder "staging" instead.
</blockquote></details>

Done.

---

*[.travis.yml, line 37 at r2](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeEoyqG0vtAfUWk-4UR:-KeEvWZ2IxDGzWQglTK5:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/1b4af85c6732f9d8782799a6963f4d2107baf615/.travis.yml#L37)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I imagined this would be `||` rather than `&&`. The thought being either we use the personal encryption key from forked repos, or we use the `m-lab/npad-support` key from `sandbox-*` branches in the npad-support repo.
</blockquote></details>

Done.

---

*[README.md, line 22 at r3](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeEr9VoApfRwhQpUTT3:-KeEuoWDg_t1xwdewBrK:b-msgk3a) ([raw file](https://github.com/m-lab/npad-support/blob/efb0795dc80aefa8b3f2b840b3cf52b46be04f0d/README.md#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

s/private/testing/ ?

Does this section need any other updates yet?
</blockquote></details>

There is already a TEST category, that goes to staging/testing.  So I prefer private here.

---

*[travis/decrypt.sh, line 9 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeBPQudsKa7KXywYvj5:-KeEvEAsDUueDkZZOl5E:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/5549d44b1b283a39c1df6ab4bdd581a58daa4247/travis/decrypt.sh#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Thank you for these detailed notes.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/27)*

**Comment by stephen-soltesz** [comment]
:lgtm:

Thanks!

---

Reviewed 1 of 2 files at r4.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 22 at r3](https://reviewable.io:443/reviews/m-lab/npad-support/27#-KeEr9VoApfRwhQpUTT3:-KeEvya81x7DCaGPCzsh:b-rrcqf5) ([raw file](https://github.com/m-lab/npad-support/blob/efb0795dc80aefa8b3f2b840b3cf52b46be04f0d/README.md#L22)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

There is already a TEST category, that goes to staging/testing.  So I prefer private here.
</blockquote></details>

Oh, right. I was mixing up the use case for private and testing folders.

Also, I read "private" as the name of the destination folder. But, that's not what the .travis.yml files does.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/27#-:-KeEx42nD0UveOJMBeyz:b9benhj)*

**Pull request merged**
