### PR TITLE
Build PT in npad

### PR DESCRIPTION
**Pull request by pboothe**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/npad-support/46)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[init/initialize.sh, line 20 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/46#-L59snRGHov2kADpYSbr:-L59snRGHov2kADpYSbs:bn5o20) ([raw file](https://github.com/m-lab/npad-support/blob/fb082f318075f1c562b189317c26a9deb049776b/init/initialize.sh#L20)):*
> ```Shell
> echo "Install required packages and perform System Update"
> yum install -y httpd gnuplot-py gnuplot
> # Commented out until fix for overlapping PT bug is in upstream .rpm
> ```

"TODO: remove comment once bug fix is deployed"

---

*[init/prepare.sh, line 51 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/46#-L59szA5bdbisUAXI5ea:-L59szA5bdbisUAXI5eb:b8c42n6) ([raw file](https://github.com/m-lab/npad-support/blob/fb082f318075f1c562b189317c26a9deb049776b/init/prepare.sh#L51)):*
> ```Shell
> # build paris-traceroute
> # Required because fix for overlapping PT bug is too new to be in upstream RPMs.
> # This code shouldbe deleted when the bugfix migrates outwards.
> ```

should be

How will we know that the bugfix has migrated outwards?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/46#-:-L59t9XxgubxNDv55PPN:bnfp4nl)*

**Comment by pboothe** [comment]
:lgtm: 

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/46#-:-L5A5qfEUQdTGiOuPL15:bg7igkv)*

**Comment by pboothe** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[init/initialize.sh, line 20 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/46#-L59snRGHov2kADpYSbr:-L5A5tqtIFnLAApXwovw:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/fb082f318075f1c562b189317c26a9deb049776b/init/initialize.sh#L20)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

"TODO: remove comment once bug fix is deployed"
</blockquote></details>

Done.

---

*[init/prepare.sh, line 51 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/46#-L59szA5bdbisUAXI5ea:-L5A5uNAvu70Sy3tlbSy:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/fb082f318075f1c562b189317c26a9deb049776b/init/prepare.sh#L51)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

should be

How will we know that the bugfix has migrated outwards?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/46)*

**Comment by pboothe** [comment]
Added an LGTM to make the Reviewable check happy.

**Pull request merged**
