### PR TITLE
Push on green

### PR DESCRIPTION
**Pull request by gfr10598**
This adds travis based building, using a docker build container.  It allows travis to do the complete rpm build, and then conditionally push it to a new rpm bucket on GCS.

If this is too much, I can reorganize it into smaller pieces.

Will need to do some further testing when this is pushed to m-lab, but seems to be doing what we want for pushes to gfr10598/npad-support.

I expect there will be a few clean ups to do.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/npad-support/21)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Reviewed 6 of 10 files at r1.
Review status: 6 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[.travis.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmjjGHZTioMB-2Gx0z:-KdmjjGHZTioMB-2Gx1-:b-urx0) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L1)):*
> ```YAML
> dist: trusty
> ```

What would you think about starting the practice of including a header comment with an outline of functionality provided by the file?

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmLi8FzDPCTP9jrecl:-KdmLi8FzDPCTP9jrecm:b-nf4ivf) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L9)):*
> ```YAML
> # If an encryption key exists, this will decrypt the service-account key.
> # m-lab repo
> - if [[ -n "$encrypted_5e545a9d5aeb_iv" ]] ; then
> ```

Oops. The encrypted iv `encrypted_5e545a9d5aeb_iv` is not the same one used on the next line.

Which key was used to encrypt `travis/legacy-rpm-writer.json.m-lab`?

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmM5TnvL2AXhsbrHQ_:-KdmM5TnvL2AXhsbrHQa:b-2j9eic) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L12)):*
> ```YAML
>   openssl aes-256-cbc -d
>   -K $encrypted_9bceeca3f3aa_key -iv $encrypted_9bceeca3f3aa_iv
>   -in $TRAVIS_BUILD_DIR/travis/legacy-rpm-writer.json.m-lab
> ```

It will become simpler over time if we adopt the same naming convention for encrypted service account files. Based on the name `legacy-rpm-writer.json.m-lab`, it's not apparent what the content of this file is.

In epoxy, we used `service-accounts.tar.enc`.
https://github.com/m-lab/epoxy/tree/dev/travis

What convention could we use for npad-support and other repos in the future?

---

*[.travis.yml, line 18 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmLOxkgnZwfT5irPSt:-KdmLOxleaV54CAnLOiD:bh6zv1g) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L18)):*
> ```YAML
>   openssl aes-256-cbc -d
>   -K $encrypted_9bceeca3f3aa_key -iv $encrypted_9bceeca3f3aa_iv
>   -in $TRAVIS_BUILD_DIR/travis/legacy-rpm-writer.json.gfr10598
> ```

I understand the desire to add encrypted files for personal repos. Does this scale well for new developers of support repos? Also, will we want deployments from personal repos in the future?

Earlier this week, we had a functional package but realized that it was built from your personal repo and so shouldn't be deployed. If we restrict deployment to builds from the upstream repo, then every rpm will come from the right place.

---

*[.travis.yml, line 22 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmOIc1TodopB5EJQ3B:-KdmOIc2J7A0_P2MwC1f:bdzex2r) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L22)):*
> ```YAML
> 
> script:
> # TODO - change to :latest
> ```

What does `:latest` refer to?

---

*[.travis.yml, line 27 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmhI_2jR_TQej4NMMZ:-KdmhI_3xs6Vz2zSUb5P:bbnema7) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L27)):*
> ```YAML
> - $TRAVIS_BUILD_DIR/travis/container_build.sh
> 
> # TODO: Travis has GCS deployment, so we should probably try using that
> ```

Possibly. Since we learned that we can write to GCS buckets using service accounts with absolutely no permissions, I suspect that using service accounts and this script is a more conservative permission model than the travis GCS deploy mechanism.

---

*[.travis.yml, line 29 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmobeQlY4uAOe49yPt:-KdmobeQlY4uAOe49yPu:bj5bi9a) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L29)):*
> ```YAML
> # TODO: Travis has GCS deployment, so we should probably try using that
> # instead of script.
> deploy:
> ```

Up to now, the build, deploy, test, rollout cycle has looked like this:

 * review & push changes to npad-support (or any support repo) master
 * build rpm from npad-support master.
 * deploy rpm to mirror testing yum repository
 * rollout to test nodes & verify correct behavior.
 * promote the exact same rpm binary to staging yum repository.
 * rollout to staging nodes & canary a few production machines with the same rpm.
 * verify correct behavior.
 * promote the exact same rpm binary to production yum repository.

In the above case we have one git repo branch and three phases of rollout, all using the same rpm built at the beginning. If we trust the review process, and that RPMs built from the same sources will behave in the same way (despite minor binary differences due to timestamps), then we have flexibility to define a new model.

The deploy modes enabled by this .travis config look like (correct me if I'm mistaken):

 * deploy testing rpms built from commits to any branch of forked repositories.
 * deploy untagged rpms built from commits to any branch on this repository.
 * deploy staging rpms built from tags

I would like to advocate for us never deploying RPMs to any M-Lab machine built from any source other than this upstream repository.

As with the development and testing of NDT, and the review and deployment steps designed into epoxy, what will be the comparable progression from less tested to more tested for RPMs built from support repos?

I would like to advocate for specific branches dedicated to specific purposes. This way if we see an RPM in a specific GCS folder, we can track it back to a specific branch and commit deterministically. I also imagine this will focus the development process.

Also, I advocate far less for myself or my preferences here than on my projection of what will ease management of and reasoning about the system we're building for those who will interact with it most at OTI.

---

*[npad, line 1 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmZhPPDiJb18TUJr-f:-KdmZhPQisOOdxmFfUVX:bh606sf) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/npad#L1)):*
> ```
> Subproject commit c15042ec0ede6c5ede35a472eec21f22d29c31f8
> ```

Confirmed that this is the upstream master head.

---

*[README.md, line 11 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-Kdmaje44A7ghaH6kO2I:-Kdmaje5g767mz_w0ISv:b-smvf28) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/README.md#L11)):*
> ```Markdown
> pull-requests trigger building the rpm on travis.
> 
> Successful pushes will also trigger writing of the rpm to google cloud
> ```

Suggest rephrasing to: "Pushes with successful builds will ..."

---

*[sidestream, line 1 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmYa6vaURH2Cl2KCHf:-KdmYa6wv9pKdpvCpiPH:b-9bzwqs) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/sidestream#L1)):*
> ```
> Subproject commit 4b5ef6d232e50afc9d9d7abe2240e92dc2056237
> ```

I had to hunt for this sha.

It looks like it's in the `canary` branch of `npad/sidestream`

https://github.com/npad/sidestream/commits/canary

Is that intentional? I couldn't find the PR with that change.

What is the difference between canary and dev?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21)*

**Comment by gfr10598** [comment]
Review status: 6 of 10 files reviewed at latest revision, 10 unresolved discussions.

---

*[.travis.yml, line 1 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmjjGHZTioMB-2Gx0z:-KdpZ1R9NysE2N9EdgjP:b-ynenh3) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What would you think about starting the practice of including a header comment with an outline of functionality provided by the file?
</blockquote></details>

Hah.  Have I created a monster?
Done.

---

*[.travis.yml, line 9 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmLi8FzDPCTP9jrecl:-KdpYqeaPhPu5AhSHRlu:bt2vr1b) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L9)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Oops. The encrypted iv `encrypted_5e545a9d5aeb_iv` is not the same one used on the next line.

Which key was used to encrypt `travis/legacy-rpm-writer.json.m-lab`?
</blockquote></details>

Fixed.

---

*[.travis.yml, line 12 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmM5TnvL2AXhsbrHQ_:-KdpjLM5--N_sgKxcCd5:b1bsnor) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L12)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

It will become simpler over time if we adopt the same naming convention for encrypted service account files. Based on the name `legacy-rpm-writer.json.m-lab`, it's not apparent what the content of this file is.

In epoxy, we used `service-accounts.tar.enc`.
https://github.com/m-lab/epoxy/tree/dev/travis

What convention could we use for npad-support and other repos in the future?
</blockquote></details>

Updated to use m-lab.enc and gfr10598.enc.  I think the json is irrelevant in this context, so I left that out.

---

*[.travis.yml, line 18 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmLOxkgnZwfT5irPSt:-KdpZKPHdqB2VWynIm0C:b7s5hyg) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L18)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I understand the desire to add encrypted files for personal repos. Does this scale well for new developers of support repos? Also, will we want deployments from personal repos in the future?

Earlier this week, we had a functional package but realized that it was built from your personal repo and so shouldn't be deployed. If we restrict deployment to builds from the upstream repo, then every rpm will come from the right place.
</blockquote></details>

Well, I've tried to address this by deploying to different folders, depending on the source and whether it is tagged.  I've documented this better.

I'm not too concerned about scaling, but we can address it if it becomes a problem.  I needed it to work for me so I could test it, and chose to leave the code in place as an example of how to do it.

As for conventions, I needed to come up with something new in order to handle forks.  Once I added a repo suffix, I didn't feel like the .enc was all that informative.  However, I'll add comments for that, too, and if you think it would be better to have the .enc as well, let me know.

---

*[.travis.yml, line 22 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmOIc1TodopB5EJQ3B:-Kdpj6h6B8cBjUT9NzlC:bj4un6m) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L22)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What does `:latest` refer to?
</blockquote></details>

Improved comment.

---

*[.travis.yml, line 27 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmhI_2jR_TQej4NMMZ:-Kdpj2htxv2kuQ3Dmb4-:bmpo6eu) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L27)):*
> process
Updated comment.

---

*[.travis.yml, line 29 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmobeQlY4uAOe49yPt:-Kdua643gUf1oiWF7XxD:b-rt1mep) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Up to now, the build, deploy, test, rollout cycle has looked like this:

 * review & push changes to npad-support (or any support repo) master
 * build rpm from npad-support master.
 * deploy rpm to mirror testing yum repository
 * rollout to test nodes & verify correct behavior.
 * promote the exact same rpm binary to staging yum repository.
 * rollout to staging nodes & canary a few production machines with the same rpm.
 * verify correct behavior.
 * promote the exact same rpm binary to production yum repository.

In the above case we have one git repo branch and three phases of rollout, all using the same rpm built at the beginning. If we trust the review process, and that RPMs built from the same sources will behave in the same way (despite minor binary differences due to timestamps), then we have flexibility to define a new model.

The deploy modes enabled by this .travis config look like (correct me if I'm mistaken):

 * deploy testing rpms built from commits to any branch of forked repositories.
 * deploy untagged rpms built from commits to any branch on this repository.
 * deploy staging rpms built from tags

I would like to advocate for us never deploying RPMs to any M-Lab machine built from any source other than this upstream repository.

As with the development and testing of NDT, and the review and deployment steps designed into epoxy, what will be the comparable progression from less tested to more tested for RPMs built from support repos?

I would like to advocate for specific branches dedicated to specific purposes. This way if we see an RPM in a specific GCS folder, we can track it back to a specific branch and commit deterministically. I also imagine this will focus the development process.

Also, I advocate far less for myself or my preferences here than on my projection of what will ease management of and reasoning about the system we're building for those who will interact with it most at OTI.
</blockquote></details>

Thanks for all these thoughtful points.  I have made some changes to the travis and readme files, so that the folder names are more self-explanatory and better documented.  I've added to the README a suggestion of how we might modify the process going forward.  If you think it doesn't belong here, let me know.

---

*[README.md, line 11 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-Kdmaje44A7ghaH6kO2I:-KdpnItqyMtoHzNZlxhY:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/README.md#L11)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Suggest rephrasing to: "Pushes with successful builds will ..."
</blockquote></details>

Done.

---

*[sidestream, line 1 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmYa6vaURH2Cl2KCHf:-KdpmkHMdBgn4flW2Ham:bvrncv8) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/sidestream#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I had to hunt for this sha.

It looks like it's in the `canary` branch of `npad/sidestream`

https://github.com/npad/sidestream/commits/canary

Is that intentional? I couldn't find the PR with that change.

What is the difference between canary and dev?
</blockquote></details>

Good catch.  I had been wondering which to use.  Changed back to master.
dev and master are the same
canary has the per-ip address logging enabled, but we can leave that for a followup deployment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21)*

**Comment by gfr10598** [comment]
*[npad, line 1 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmZhPPDiJb18TUJr-f:-KdubM5SLBzJ_idDwwdg:b2nhysk) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/npad#L1)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Confirmed that this is the upstream master head.
</blockquote></details>

ack

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21)*

**Comment by stephen-soltesz** [comment]
Review status: 5 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 29 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmobeQlY4uAOe49yPt:-Ke-Gu-tgEaB0Nke4hSc:b-ygjgq) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L29)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Thanks for all these thoughtful points.  I have made some changes to the travis and readme files, so that the folder names are more self-explanatory and better documented.  I've added to the README a suggestion of how we might modify the process going forward.  If you think it doesn't belong here, let me know.
</blockquote></details>

We discussed in person some of the existing [Conventions for M-Lab Release Automation](https://docs.google.com/document/d/1p1Izr5rzTHGP7ErOsqWvEcJqahdiXO0bx8sHtVbZ0fI/edit#heading=h.1w4h8y8s4bx8) and how there may be a way to map the use-cases from rpm building to our current conventions.

For example:

 * We could use `sandbox-*`branches to generate "unreviewed" rpms. This is a new use case.
 * We could use `dev` branch for review of new code changes. Then, merged PRs would generate a "testing" rpm. This would correspond to the "testing" yum repo used today and feed into the existing NDT e2e test process.
 * After a successful test, we could tag the commit. This would generate a "staging" rpm. We would canary this RPM to some production machines.
 * After successful canary of the staging RPM, we could promote the same RPM to "production", and merge the `dev` branch into the `master` branch. Since the tag is associated with a git hash, master is now tagged as well.

How does this sound?

If we adopt this approach, then we do not need the per-user encrypted keys.
As well, we'll have a clear mapping from git branches to folders in gcs to rpm yum repos and the current testing process (only used for ndt, but this is an opportunity to extend it to npad as well).

---

*[travis/README.md, line 8 at r2](https://reviewable.io:443/reviews/m-lab/npad-support/21#-Ke-2rZCmhqGPg7rEYOL:-Ke-2rZCmhqGPg7rEYOM:bm5miie) ([raw file](https://github.com/m-lab/npad-support/blob/968198405e3e431f68f90259ef2bb2a0b644ab24/travis/README.md#L8)):*
> ```Markdown
> 
> * legacy-rpm-writer.*.enc - encrypted key files for access to GCS.
> These contain the same content, but are encrypted with different keys.
> ```

Please mention that these are GCP service accounts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21)*

**Comment by gfr10598** [comment]
Review status: 5 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[.travis.yml, line 29 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmobeQlY4uAOe49yPt:-Ke0HNrisxFYCRJjj2-B:banapcr) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L29)):*
> e could use sandbox-*branches to generate "unreviewed" rpms. This is a new use case.
> We could use dev branch for review of new code changes. Then, merged PRs would generate a "testing" rpm. This would correspond to the "testing" yum repo used today and feed into the existing NDT e2e test process.
> After a successful test, we could tag the commit. This would generate a "staging" rpm. We would canary this RPM to some production machines.
> After successful canary of the staging RPM, we could promote the same RPM to "production", and merge the dev branch into the master branch. Since the tag is associated with a git hash, master is now tagged as well.

SGTM.  I will update outline in README.  What do you think about leaving the code as is for now, (including the private credentials) and tweaking it in future PRs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21)*

**Comment by gfr10598** [comment]
*[travis/README.md, line 8 at r2](https://reviewable.io:443/reviews/m-lab/npad-support/21#-Ke-2rZCmhqGPg7rEYOL:-Ke0L_xcfqW9yJOEyyWM:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/968198405e3e431f68f90259ef2bb2a0b644ab24/travis/README.md#L8)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please mention that these are GCP service accounts.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21)*

**Comment by stephen-soltesz** [comment]
Thanks, Greg.  If you agree that the outline in the README is the plan, then please add two TODOs, and LGTM.

:lgtm:

---

Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 29 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmobeQlY4uAOe49yPt:-Ke0XYe_X06QB3t0Bzmp:b-supk98) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L29)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

> e could use sandbox-*branches to generate "unreviewed" rpms. This is a new use case.
> We could use dev branch for review of new code changes. Then, merged PRs would generate a "testing" rpm. This would correspond to the "testing" yum repo used today and feed into the existing NDT e2e test process.
> After a successful test, we could tag the commit. This would generate a "staging" rpm. We would canary this RPM to some production machines.
> After successful canary of the staging RPM, we could promote the same RPM to "production", and merge the dev branch into the master branch. Since the tag is associated with a git hash, master is now tagged as well.

SGTM.  I will update outline in README.  What do you think about leaving the code as is for now, (including the private credentials) and tweaking it in future PRs
</blockquote></details>

No problem. If you agree that the outline in the README is the plan, then please add two TODOs: one to remove the gfr10598 key, and another to update the `deploy` block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21#-:-Ke0YnPaUA_X4mgGeTwg:b-deao9d)*

**Comment by gfr10598** [comment]
Review status: 5 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 29 at r1](https://reviewable.io:443/reviews/m-lab/npad-support/21#-KdmobeQlY4uAOe49yPt:-Ke0ts5dEzAI-ViwRBY0:b-896fix) ([raw file](https://github.com/m-lab/npad-support/blob/4417bf209f75e41d34f09fbe0a22d841b9dc15bc/.travis.yml#L29)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

No problem. If you agree that the outline in the README is the plan, then please add two TODOs: one to remove the gfr10598 key, and another to update the `deploy` block.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/npad-support/21)*

**Pull request merged**
